# Generated by Django 4.2.1 on 2025-10-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=100)),
                ('edept', models.CharField(max_length=100)),
                ('esal', models.FloatField()),
                ('eid', models.IntegerField()),
                ('enationality', models.CharField(max_length=100)),
            ],
        ),
    ]
